apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
  - name: init-download
    image: busybox:1.36
    command: ['sh', '-c', 'wget -O /work-dir/index.html https://example.com']
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  - name: wait-for-service
    image: busybox:1.36
    command: ['sh', '-c', 'until nslookup vault; do sleep 2; done']
  containers:
  - name: main-app
    image: busybox:1.36
    command: ['sh', '-c', 'cat /data/index.html && sleep 3600']
    volumeMounts:
    - name: workdir
      mountPath: /data
  volumes:
  - name: workdir
    emptyDir: {}