services:
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/config.yml
    networks:
      - loki-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail/config.yaml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - loki-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - loki-network
    restart: unless-stopped

  app-python:
    image: projacktor/python-info-service:latest
    ports:
      - "5000:5000"
    networks:
      - loki-network
    labels:
      logging: "promtail"
      app: "devops-python"

volumes:
  loki-data:
    driver: local
  grafana-data:
    driver: local

networks:
  loki-network:
    driver: bridge
