{{- if and .Values.hooks.enabled .Values.hooks.preInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "python-info-service.fullname" . }}-pre-install
  labels:
    {{- include "python-info-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "{{ .Values.hooks.preInstall.weight }}"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      labels:
        {{- include "python-info-service.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install-job
          image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          imagePullPolicy: {{ .Values.hooks.image.pullPolicy }}
          command:
            {{- toYaml .Values.hooks.preInstall.command | nindent 12 }}
{{- end }}
