{
 "title": "Prometheus dashb",
 "time": { "from": "2026-03-19T15:17:50.995Z", "to": "2026-03-19T17:47:53.848Z" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(devops_info_system_collection_seconds_sum[5m])) / sum(rate(devops_info_system_collection_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Duration p95 (Graph)",
   "type": "timeseries",
   "description": "Request Duration p95 (Graph)",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code Distribution (Pie Chart)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (stat)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"app-python\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (Graph)",
   "type": "nodeGraph",
   "description": "Error Rate (Graph)",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request Rate (Graph)",
   "type": "timeseries",
   "description": "Request Rate (Graph)",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (endpoint)"
    }
   ]
  }
 ]
}