apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-info-service.fullname" . }}-config
  labels:
    {{- include "python-info-service.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}
