apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-info-service.fullname" . }}
  labels:
    {{- include "python-info-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "python-info-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "python-info-service.selectorLabels" . | nindent 8 }}
      {{- if .Values.vault.enabled }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-{{ .Values.vault.injectFile }}: {{ .Values.vault.secretPath | quote }}
        vault.hashicorp.com/agent-inject-template-{{ .Values.vault.injectFile }}: |
          {{ "{{- with secret \"" }}{{ .Values.vault.secretPath }}{{ "\" -}}" }}
          export APP_USERNAME="{{ "{{ .Data.data.username }}" }}"
          export APP_PASSWORD="{{ "{{ .Data.data.password }}" }}"
          {{ "{{- end }}" }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ include "python-info-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "python-info-service.fullname" . }}-env
          {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ default (printf "%s-credentials" (include "python-info-service.fullname" .)) .Values.secrets.name }}
          {{- end }}
          volumeMounts:
            - name: app-config
              mountPath: /config/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: {{ include "python-info-service.fullname" . }}-config
            items:
              - key: config.json
                path: config.json
