{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-credentials" (include "python-info-service.fullname" .)) .Values.secrets.name }}
  labels:
    {{- include "python-info-service.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.data.username | b64enc | quote }}
  password: {{ .Values.secrets.data.password | b64enc | quote }}
{{- end }}
