{{- if .Values.statefulset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-info-service.fullname" . }}-headless
  labels:
    {{- include "python-info-service.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "python-info-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
