replicaCount: 3

nameOverride: ""
fullnameOverride: ""

image:
  repository: projacktor/python-info-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

hooks:
  enabled: true
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  preInstall:
    enabled: true
    weight: "-5"
    command:
      - sh
      - -c
      - echo Pre-install validation started && sleep 5 && echo Pre-install validation finished
  postInstall:
    enabled: true
    weight: "5"
    command:
      - sh
      - -c
      - echo Post-install smoke test started && sleep 5 && echo Post-install smoke test finished
